# Generated by Django 2.2.3 on 2019-07-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('audit_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('message', models.TextField(verbose_name='Message')),
                ('code', models.IntegerField(verbose_name='Code')),
            ],
            options={
                'db_table': 'audit',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Amount')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('shipped_on', models.DateTimeField(blank=True, null=True, verbose_name='Shipping Time')),
                ('status', models.IntegerField(choices=[(0, 'Processing'), (1, 'Confirmed'), (2, 'Cancelled')], default=0, verbose_name='Order Status')),
                ('comments', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comments')),
                ('auth_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Authentication Code')),
                ('reference', models.CharField(blank=True, max_length=50, null=True, verbose_name='Reference')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('attributes', models.CharField(max_length=1000, verbose_name='Attributes')),
                ('product_name', models.CharField(max_length=100, verbose_name='Product Name')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Cost')),
            ],
            options={
                'db_table': 'order_detail',
            },
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('shipping_id', models.AutoField(primary_key=True, serialize=False)),
                ('shipping_type', models.CharField(max_length=100, verbose_name='Type')),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cost')),
            ],
            options={
                'db_table': 'shipping',
            },
        ),
        migrations.CreateModel(
            name='ShippingRegion',
            fields=[
                ('shipping_region_id', models.AutoField(primary_key=True, serialize=False)),
                ('shipping_region', models.CharField(max_length=100, verbose_name='Shipping Region')),
            ],
            options={
                'db_table': 'shipping_region',
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('cart_id', models.CharField(max_length=32, verbose_name='Cart ID')),
                ('attributes', models.CharField(max_length=1000, verbose_name='Attributes')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('buy_now', models.BooleanField(default=True, verbose_name='Buy Now')),
                ('added_on', models.DateTimeField(auto_now_add=True, verbose_name='Added Time')),
            ],
            options={
                'db_table': 'shopping_cart',
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('tax_id', models.AutoField(primary_key=True, serialize=False)),
                ('tax_type', models.CharField(max_length=100, verbose_name='Type')),
                ('tax_percentage', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Percentage')),
            ],
            options={
                'db_table': 'tax',
            },
        ),
    ]
