if: branch = master
language: node_js
services:
  - mysql
  - redis-server
env:
  - APP="eCommerceApi" DB_NAME="app" DB_HOST="localhost" DB_USER="root" DB_PASS="" DB_PORT="3306" REDIS_HOST="localhost" REDIS_PORT="6379" AUTH0_SECRET="(oZhS6OJQ9s&_J52KqyU*BWgQX-vWbuigQl#7btZM0(2!1rVW(#cu&X@2qInY03o" AUTH0_ID="U18Wci8fuZ!UVWQGwD9sg0m%PbJXzLmF" SNYK_TOKEN="33b4c2d8-a3e6-4165-b4a1-5528fd72de20"
node_js:
  - 'stable'
before_install:
  - npm install -g nodemon mocha nyc snyk
  - rm -f .yarnclean
  - cp -n .env.travis .env
before_script:
  - mysql --version
  - chmod +x ./reset-db.sh
script:
  - npm test
after_script:
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls